

const productos = [
    {
        id:1,
        nombre: "Casco S-Works Variante 1",
        precio:230000,
        imagen:"./assets/product_images/accesorio1.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:2,
        nombre: "Casco S-Works Variante 2",
        precio:235000,
        imagen:"./assets/product_images/accesorio2.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:3,
        nombre: "Casco S-Works Variante 3",
        precio:200000,
        imagen:"./assets/product_images/accesorio3.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:3,
        nombre: "Casco S-Works Variante 3",
        precio:200000,
        imagen:"./assets/product_images/accesorio4.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:4,
        nombre: "Casco Ergonómico Genérico",
        precio:130000,
        imagen:"./assets/product_images/accesorio5.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:5,
        nombre: "Guantes Cerrados Génericos",
        precio:45000,
        imagen:"./assets/product_images/accesorio6.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:6,
        nombre: "Guantes Probike de Ebilla",
        precio:100000,
        imagen:"./assets/product_images/accesorio7.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:7,
        nombre: "Guantes BKS de Ebilla",
        precio:110000,
        imagen:"./assets/product_images/accesorio7.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:8,
        nombre: "Gafas Clásicas lentes intercambiables",
        precio:120000,
        imagen:"./assets/product_images/accesorio8.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:9,
        nombre: "Gafas Clásicas Lentes Fotocromáticos",
        precio:120000,
        imagen:"./assets/product_images/accesorio9.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:10,
        nombre: "Gafas Lente Oscuro West-biking",
        precio:120000,
        imagen:"./assets/product_images/accesorio10.jpg",
        descripcion:"",
        categoria: "accesorios",
    },
    {
        id:21,
        nombre: "Bicicleta Gravel Scott Syncros",
        precio:5000000,
        imagen:"./assets/product_images/gravel1.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:22,
        nombre: "Bicicleta Gravel Umarin",
        precio:5000000,
        imagen:"./assets/product_images/gravel2.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:23,
        nombre: "Bicicleta Gravel Taroko Fina",
        precio:5000000,
        imagen:"./assets/product_images/gravel3.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:24,
        nombre: "Bicicleta Gravel Bombtrack",
        precio:4500000,
        imagen:"./assets/product_images/gravel4.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:25,
        nombre: "Bicicleta Gravel Jakar",
        precio:7000000,
        imagen:"./assets/product_images/gravel5.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:26,
        nombre: "Bicicleta Gravel Scott Coster",
        precio:7000000,
        imagen:"./assets/product_images/gravel6.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:27,
        nombre: "Bicicleta Gravel Bike Racer",
        precio:9000000,
        imagen:"./assets/product_images/gravel7.jpg",
        descripcion:"",
        categoria: "gravel",
    },
    {
        id:31,
        nombre: "Bicicleta Gw Zebra",
        precio:1000000,
        imagen:"./assets/product_images/montana1.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:32,
        nombre: "Bicicleta Gw Raven",
        precio:3000000,
        imagen:"./assets/product_images/montana2.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:33,
        nombre: "Bicicleta Gw Titán",
        precio:900000,
        imagen:"./assets/product_images/montana3.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:34,
        nombre: "Bicicleta Venzo Hips",
        precio:3000000,
        imagen:"./assets/product_images/montana4.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:35,
        nombre: "Bicicleta Venzo Kid",
        precio:1100000,
        imagen:"./assets/product_images/montana5.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:36,
        nombre: "Bicicleta Venzo Kid II",
        precio:1300000,
        imagen:"./assets/product_images/montana6.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:37,
        nombre: "Bicicleta Venzo Raptor",
        precio:1700000,
        imagen:"./assets/product_images/montana7.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:38,
        nombre: "Bicicleta Venzo Kid III",
        precio:1500000,
        imagen:"./assets/product_images/montana8.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:39,
        nombre: "Bicicleta Specialized Pro",
        precio:7500000,
        imagen:"./assets/product_images/montana9.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:40,
        nombre: "Bicicleta Specialized Pro II",
        precio:8500000,
        imagen:"./assets/product_images/montana10.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:41,
        nombre: "Bicicleta Specialized Pro III",
        precio:9500000,
        imagen:"./assets/product_images/montana11.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:42,
        nombre: "Bicicleta Specialized Pro Race",
        precio:10500000,
        imagen:"./assets/product_images/montana12.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:43,
        nombre: "Bicicleta Specialized Pro Race II",
        precio:11500000,
        imagen:"./assets/product_images/montana13.jpg",
        descripcion:"",
        categoria: "montana",
    },
    {
        id:51,
        nombre: "Bicicleta Gw K2",
        precio:1500000,
        imagen:"./assets/product_images/ruta1.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:52,
        nombre: "Bicicleta Gw K2 Freno disco",
        precio:2500000,
        imagen:"./assets/product_images/ruta2.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:53,
        nombre: "Bicicleta Specialized Carbon",
        precio:1000000,
        imagen:"./assets/product_images/ruta3.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:54,
        nombre: "Bicicleta Specialized Venturais",
        precio:2000000,
        imagen:"./assets/product_images/ruta4.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:55,
        nombre: "Bicicleta Specialized E-green",
        precio:1200000,
        imagen:"./assets/product_images/ruta5.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:56,
        nombre: "Bicicleta Specialized Advanter",
        precio:1000000,
        imagen:"./assets/product_images/ruta6.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:57,
        nombre: "Bicicleta Specialized E-green II",
        precio:1500000,
        imagen:"./assets/product_images/ruta7.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:58,
        nombre: "Bicicleta Trek Alpha",
        precio:2200000,
        imagen:"./assets/product_images/ruta8.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:59,
        nombre: "Bicicleta Treck Aluminium",
        precio:700000,
        imagen:"./assets/product_images/ruta9.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:60,
        nombre: "Bicicleta Orbea Classic",
        precio:20000000,
        imagen:"./assets/product_images/ruta10.jpg",
        descripcion:"",
        categoria: "ruta",
    },
    {
        id:61,
        nombre: "Bicicleta Orbea Mountain",
        precio:1100000,
        imagen:"./assets/product_images/ruta11.jpg",
        descripcion:"",
        categoria: "ruta",
    },
]


const obtenerProductos = () => {
    return new Promise ((resolve, reject) => {
        setTimeout(()=> {
            resolve(productos)
        },2000)
    })
}

export default obtenerProductos